<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="DTOs\" />
    <Folder Include="Features\Consultations\Commands\" />
    <Folder Include="Features\Consultations\Queries\" />
    <Folder Include="Features\Conversations\Commands\" />
    <Folder Include="Features\Conversations\DTOs\" />
    <Folder Include="Features\Conversations\Queries\" />
    <Folder Include="Features\Conversations\Validators\" />
    <Folder Include="Features\Payments\Commands\" />
    <Folder Include="Features\Payments\Queries\" />
    <Folder Include="Features\Users\Commands\" />
    <Folder Include="Features\Users\Queries\" />
    <Folder Include="Validators\" />
    <Folder Include="UseCases\" />
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Mapster" Version="10.0.7" />
    <PackageReference Include="Mapster.DependencyInjection" Version="10.0.7" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="11.0.0" />
  </ItemGroup>

</Project>
